### ISSUE TITLE
[Community] Create development mailer for GetNighthawk contributors

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#44]
Those participating in GetNighthawk will benefit from a mailing list as a form of asynchronous communication.

**Comment by Abhijay007** [comment]
Do we need to create a "newsletter component" ? that may get embed in footer so that nighthawk contributors, users, maintainers get a specified mail and when they enter their emails id's they get subscribed to the mailing list of this specific project? 

we have something similar in the layer5.io site and meshery site too right? ( but I think is for all mails after by layer and meshery community )

is am taking this right or is it is something else?

**Comment by leecalcote** [comment]
This one was really for me to create a Google Group mailing list, which I believe we have now (see the mailing list section on the main page). Yes, you're right - we essentially want the same thing that we have on amp-spec.io and meshery.io. We essentially have that now, but are missing two things:

1. a text field to receive visitor's email address, so that they can subscribe to the community mailer. Example - https://smp-spec.io#subscribe
2. a formatting issue on https://getnighthawk.dev/subscribe. Margin is needed to separate the nav bar and prevent overlap:
<img width="471" alt="Screen Shot 2021-12-23 at 10 45 59 AM" src="https://user-images.githubusercontent.com/7570704/147269670-25a1c672-0233-4375-abd2-80e8e890fa20.png">

**Comment by leecalcote** [comment]
I've opened a new issue to track these two items, please comment, if you would like it assigned to you, @Abhijay007.
